### ISSUE TITLE
Not in APPS

### ISSUE THREAD

**Issue by noinip** [addy90/lgogdownloader#1]
On unraid I can't find lgogdownloader at all.

**Comment by addy90** [comment]
Hi @noinip,
did you click on the "Click Here To Get More Results From DockerHub" link on the right side after searching?
The Apps (Community Applications) plugin by default only searches its own database, but allows searching on DockerHub in an additional step.
As this Docker App is published via DockerHub, you need to click on the corresponding link after the first search.

Please tell me if this helped!

**Comment by noinip** [comment]
I did not and I'm sure that was my issue. Didn't realize I needed to do
that but I know exactly what you're talking about. Thanks!

**Comment by addy90** [comment]
I updated the description (README here and on DockerHub) and added a hint to the described link. I hope this prevents future issues like yours.
If there is any other problem, please feel free to open a new Issue! Thank you!
