### ISSUE TITLE
Version 3.12 on DockerHub does not work

### ISSUE THREAD

**Issue by cschneid** [addy90/lgogdownloader#2]
This is an old project, so it's probably half abandoned. But the version prebuilt on dockerhub is `LGOGDownloader 3.12.b5e1aa8` which does not currently work with GOG. 

https://github.com/Sude-/lgogdownloader/issues/280 is the issue.

I can fork this myself of course, but wanted to at least leave some papertrail if anybody else runs into this. Everything else about this dockerfile looks great, and it sets up on unraid easy enough.

**Comment by addy90** [comment]
Hi @cschneid,

I did not update my GOG library backup for some time now, so I did not notice yet that the current image does not work anymore. However, it is not abandoned.

I made an update to the Dockerfile and built a new image and pushed it to the Dockerhub.
Should show an update button in Unraid. Can you please try out if it works again?

Thank you!

**Comment by cschneid** [comment]
What amazing response time on a years old project :) 

It is running now, well past when the error occurred. I appreciate it!

**Comment by addy90** [comment]
Thank you for reporting to me! 😃 
And thank you for your quick test that it works again!
